name: CI

on:
  push:
    branches: [ main ]
  pull_request: null

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Set up Rust
      - name: Set up Rust toolchain
        uses: dsherret/rust-toolchain-file@v1
      
      # Cache Rust dependencies
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      # Run the CI checks
      - name: CI checks
        run: ./ci.sh
