name: CI

on:
  push:
    branches: [ main ]
  pull_request: null

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      
      # This is a separate step from caching dependencies to avoid invalidating the toolchain cache when dependencies
      # change.
      - name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
          key: ${{ runner.os }}-rustup-${{ hashFiles('**/rust-toolchain.toml') }}
      
      - name: Set up Rust toolchain
        uses: dsherret/rust-toolchain-file@v1
        
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run CI checks
        run: ./ci.sh
